2025-08-13T22:02:45: Error occurred: {
  error: 'invalid input syntax for type timestamp: "22:02:44"',
  stack: 'error: invalid input syntax for type timestamp: "22:02:44"\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:769:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:02:45.879Z'
}
2025-08-13T22:02:46: Error occurred: {
  error: 'invalid input syntax for type timestamp: "22:02:44"',
  stack: 'error: invalid input syntax for type timestamp: "22:02:44"\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:769:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:02:46.964Z'
}
2025-08-13T22:02:49: Error occurred: {
  error: 'invalid input syntax for type timestamp: "22:02:44"',
  stack: 'error: invalid input syntax for type timestamp: "22:02:44"\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:769:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:02:49.062Z'
}
2025-08-13T22:17:03: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:03.545Z'
}
2025-08-13T22:17:04: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:04.624Z'
}
2025-08-13T22:17:06: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:06.703Z'
}
2025-08-13T22:17:33: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:33.723Z'
}
2025-08-13T22:17:34: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:34.802Z'
}
2025-08-13T22:17:36: Error occurred: {
  error: 'null value in column "machine_id" of relation "attendance_register" violates not-null constraint',
  stack: 'error: null value in column "machine_id" of relation "attendance_register" violates not-null constraint\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:17:36.883Z'
}
2025-08-13T22:26:27: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:27.068Z'
}
2025-08-13T22:26:28: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:28.143Z'
}
2025-08-13T22:26:30: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:30.063Z'
}
2025-08-13T22:26:30: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:30.214Z'
}
2025-08-13T22:26:31: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:31.643Z'
}
2025-08-13T22:26:33: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:33.724Z'
}
2025-08-13T22:26:37: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:37.333Z'
}
2025-08-13T22:26:38: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:38.415Z'
}
2025-08-13T22:26:40: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:40.504Z'
}
2025-08-13T22:26:48: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:48.503Z'
}
2025-08-13T22:26:49: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:49.573Z'
}
2025-08-13T22:26:51: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:26:51.649Z'
}
2025-08-13T22:28:12: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:28:12.907Z'
}
2025-08-13T22:28:14: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:28:14.071Z'
}
2025-08-13T22:28:16: Error occurred: {
  error: 'there is no unique or exclusion constraint matching the ON CONFLICT specification',
  stack: 'error: there is no unique or exclusion constraint matching the ON CONFLICT specification\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)\n' +
    '    at async LaborService.markAttendance (/home/production-app/production-orders-app/src/services/labor.service.js:791:20)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/labor.routes.js:299:30',
  url: '/attendance-register',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T20:28:16.170Z'
}
2025-08-13T23:57:54: JWT verification failed: jwt malformed
2025-08-14T00:01:05: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:318:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:182:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:01:26: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:318:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:182:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:10:59: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:12:52: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:12:58: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:12:58.213Z'
}
2025-08-14T00:12:59: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:12:59.282Z'
}
2025-08-14T00:13:01: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:13:01.351Z'
}
2025-08-14T00:13:43: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:15:22: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:15:25: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/38',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:15:25.732Z'
}
2025-08-14T00:15:26: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/38',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:15:26.820Z'
}
2025-08-14T00:15:28: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/38',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:15:28.903Z'
}
2025-08-14T00:17:28: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:17:33: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:17:48: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:48.652Z'
}
2025-08-14T00:17:49: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:49.728Z'
}
2025-08-14T00:17:51: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:51.801Z'
}
2025-08-14T00:17:51: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:51.929Z'
}
2025-08-14T00:17:52: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:52.999Z'
}
2025-08-14T00:17:55: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:17:55.082Z'
}
2025-08-14T00:23:18: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:24:22: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:24:26: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:24:26.191Z'
}
2025-08-14T00:24:27: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:24:27.266Z'
}
2025-08-14T00:24:29: Error occurred: {
  error: 'column "order_number" of relation "machines" does not exist',
  stack: 'error: column "order_number" of relation "machines" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.update (/home/production-app/production-orders-app/src/utils/database.js:86:20)\n' +
    '    at async MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:140:28)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/40',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-13T22:24:29.349Z'
}
2025-08-14T00:27:24: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:27:31: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:27:56: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:30:06: Error occurred: {
  error: 'Cannot change status while machine is in use or paused',
  stack: 'ValidationError: Cannot change status while machine is in use or paused\n' +
    '    at MachinesService.updateMachineStatus (/home/production-app/production-orders-app/src/services/machines.service.js:167:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:176:28',
  url: '/api/machines/24/status',
  method: 'PATCH',
  user: 'admin',
  timestamp: '2025-08-13T22:30:06.694Z'
}
2025-08-14T00:30:20: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:32:03: Error getting machine crews: error: column "crew_data" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.getMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:350:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:194:19 {
  length: 109,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '17',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3722',
  routine: 'errorMissingColumn'
}
2025-08-14T00:32:07: Error saving machine crews: error: column "crew_data" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:32:07: Error occurred: {
  error: 'Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:32:07.084Z'
}
2025-08-14T00:32:08: Error saving machine crews: error: column "crew_data" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:32:08: Error occurred: {
  error: 'Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:32:08.153Z'
}
2025-08-14T00:32:10: Error saving machine crews: error: column "crew_data" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 135,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '49',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:32:10: Error occurred: {
  error: 'Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "crew_data" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:32:10.223Z'
}
2025-08-14T00:33:29: Error saving machine crews: error: column "updated_by" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 136,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:33:29: Error occurred: {
  error: 'Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:33:29.156Z'
}
2025-08-14T00:33:30: Error saving machine crews: error: column "updated_by" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 136,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:33:30: Error occurred: {
  error: 'Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:33:30.242Z'
}
2025-08-14T00:33:32: Error saving machine crews: error: column "updated_by" of relation "machine_crews" does not exist
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:397:22)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20 {
  length: 136,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '72',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
2025-08-14T00:33:32: Error occurred: {
  error: 'Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist',
  stack: 'Error: Failed to save machine crews: column "updated_by" of relation "machine_crews" does not exist\n' +
    '    at MachinesService.saveMachineCrews (/home/production-app/production-orders-app/src/services/machines.service.js:411:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:213:20',
  url: '/api/machines/40/crews',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-13T22:33:32.311Z'
}
2025-08-14T00:39:59: JWT verification failed: jwt expired
2025-08-14T00:39:59: JWT verification failed: jwt expired
2025-08-14T00:39:59: JWT verification failed: jwt expired
2025-08-14T00:40:00: JWT verification failed: jwt expired
2025-08-14T00:40:02: JWT verification failed: jwt expired
2025-08-14T00:42:15: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T00:45:28: JWT verification failed: jwt malformed
2025-08-14T08:00:15: Error occurred: {
  error: 'column "customer_info" of relation "production_orders" does not exist',
  stack: 'error: column "customer_info" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.insert (/home/production-app/production-orders-app/src/utils/database.js:61:20)\n' +
    '    at async OrdersService.createOrder (/home/production-app/production-orders-app/src/services/orders.service.js:102:22)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:197:22',
  url: '/api/orders',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:00:15.708Z'
}
2025-08-14T08:00:16: Error occurred: {
  error: 'column "customer_info" of relation "production_orders" does not exist',
  stack: 'error: column "customer_info" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.insert (/home/production-app/production-orders-app/src/utils/database.js:61:20)\n' +
    '    at async OrdersService.createOrder (/home/production-app/production-orders-app/src/services/orders.service.js:102:22)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:197:22',
  url: '/api/orders',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:00:16.761Z'
}
2025-08-14T08:00:18: Error occurred: {
  error: 'column "customer_info" of relation "production_orders" does not exist',
  stack: 'error: column "customer_info" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)\n' +
    '    at async DatabaseUtils.insert (/home/production-app/production-orders-app/src/utils/database.js:61:20)\n' +
    '    at async OrdersService.createOrder (/home/production-app/production-orders-app/src/services/orders.service.js:102:22)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:197:22',
  url: '/api/orders',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:00:18.807Z'
}
2025-08-14T08:12:13: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T08:12:13: 🔒 Auth failure: admin from ::1 - Invalid credentials - curl/8.5.0
2025-08-14T08:12:19: 🔒 Auth failure: admin from ::1 - Invalid credentials - curl/8.5.0
2025-08-14T08:12:31: 🔒 Auth failure: Brandon King from ::ffff:127.0.0.1 - Invalid credentials - curl/8.5.0
2025-08-14T08:12:43: 🔒 Auth failure: admin from ::1 - Invalid input - curl/8.5.0
2025-08-14T08:50:18: Error occurred: {
  error: 'Cannot update machine while in use',
  stack: 'ValidationError: Cannot update machine while in use\n' +
    '    at MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:128:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/32',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-14T06:50:18.383Z'
}
2025-08-14T08:50:29: Error occurred: {
  error: 'Only in-progress orders can be completed',
  stack: 'ValidationError: Only in-progress orders can be completed\n' +
    '    at OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:218:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:29.042Z'
}
2025-08-14T08:50:30: Error occurred: {
  error: 'Only in-progress orders can be completed',
  stack: 'ValidationError: Only in-progress orders can be completed\n' +
    '    at OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:218:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:30.386Z'
}
2025-08-14T08:50:39: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:39.205Z'
}
2025-08-14T08:50:40: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:40.252Z'
}
2025-08-14T08:50:42: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:42.291Z'
}
2025-08-14T08:50:44: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:44.186Z'
}
2025-08-14T08:50:45: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:45.287Z'
}
2025-08-14T08:50:47: Error occurred: {
  error: 'column "waste_quantity" of relation "production_orders" does not exist',
  stack: 'error: column "waste_quantity" of relation "production_orders" does not exist\n' +
    '    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async DatabaseManager.transaction (/home/production-app/production-orders-app/src/config/database.js:56:24)\n' +
    '    at async DatabaseUtils.transaction (/home/production-app/production-orders-app/src/utils/database.js:153:12)\n' +
    '    at async OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:229:21)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/80/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:50:47.345Z'
}
2025-08-14T08:51:12: Error occurred: {
  error: 'Only in-progress orders can be completed',
  stack: 'ValidationError: Only in-progress orders can be completed\n' +
    '    at OrdersService.completeOrder (/home/production-app/production-orders-app/src/services/orders.service.js:218:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/orders.routes.js:388:28',
  url: '/api/orders/82/complete',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-14T06:51:12.590Z'
}
2025-08-14T15:23:24: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T16:27:23: Error occurred: {
  error: 'Cannot update machine while in use',
  stack: 'ValidationError: Cannot update machine while in use\n' +
    '    at MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:128:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/23',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-14T14:27:23.763Z'
}
2025-08-14T18:00:29: JWT verification failed: jwt expired
2025-08-14T18:00:29: JWT verification failed: jwt expired
2025-08-14T18:00:31: JWT verification failed: jwt expired
2025-08-14T18:00:33: JWT verification failed: jwt expired
2025-08-14T18:00:57: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T18:22:55: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T21:00:00: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T22:04:05: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-14T22:08:27: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-15T16:07:29: JWT verification failed: jwt expired
2025-08-15T16:07:29: JWT verification failed: jwt expired
2025-08-15T16:07:29: JWT verification failed: jwt expired
2025-08-15T16:07:30: JWT verification failed: jwt expired
2025-08-15T16:07:32: JWT verification failed: jwt expired
2025-08-15T16:07:35: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-15T16:47:17: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-15T16:54:55: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 427,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (7, 40, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:54:55.984626+02, 2025-08-15 16:54:55.984626+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:54:55: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:54:55.989Z'
}
2025-08-15T16:54:56: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 427,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (8, 40, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:54:56.888489+02, 2025-08-15 16:54:56.888489+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:54:56: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:54:56.889Z'
}
2025-08-15T16:54:57: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 427,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (9, 40, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:54:57.074625+02, 2025-08-15 16:54:57.074625+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:54:57: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:54:57.076Z'
}
2025-08-15T16:54:57: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (10, 40, undefined, 0, [{"id":13,"username":"andile msani","full_name":"andile msani","..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:54:57.865819+02, 2025-08-15 16:54:57.865819+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:54:57: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:54:57.867Z'
}
2025-08-15T16:54:58: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (11, 40, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:54:58.020657+02, 2025-08-15 16:54:58.020657+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:54:58: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:54:58.022Z'
}
2025-08-15T16:54:58: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T16:54:58: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/10',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T14:54:58.817Z'
}
2025-08-15T16:54:58: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (12, 40, undefined, 0, [{"id":13,"username":"andile msani","full_name":"andile msani","..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:54:58.911683+02, 2025-08-15 16:54:58.911683+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:54:58: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:54:58.913Z'
}
2025-08-15T16:54:59: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (13, 40, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:54:59.178249+02, 2025-08-15 16:54:59.178249+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:54:59: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:54:59.179Z'
}
2025-08-15T16:55:00: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T16:55:00: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/10',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T14:55:00.357Z'
}
2025-08-15T16:55:00: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (14, 40, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:00.362484+02, 2025-08-15 16:55:00.362484+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:00: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:00.364Z'
}
2025-08-15T16:55:01: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (15, 40, undefined, 0, [{"id":13,"username":"andile msani","full_name":"andile msani","..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:01.299824+02, 2025-08-15 16:55:01.299824+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:01: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:01.301Z'
}
2025-08-15T16:55:02: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T16:55:02: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/10',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T14:55:02.407Z'
}
2025-08-15T16:55:07: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (16, 38, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:07.512739+02, 2025-08-15 16:55:07.512739+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:07: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/38/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:07.513Z'
}
2025-08-15T16:55:08: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (17, 38, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:08.189064+02, 2025-08-15 16:55:08.189064+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:08: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/38/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:08.190Z'
}
2025-08-15T16:55:08: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (18, 38, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:08.558636+02, 2025-08-15 16:55:08.558636+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:08: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/38/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:08.560Z'
}
2025-08-15T16:55:09: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (19, 38, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:09.236144+02, 2025-08-15 16:55:09.236144+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:09: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/38/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:09.237Z'
}
2025-08-15T16:55:10: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (20, 38, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:10.610649+02, 2025-08-15 16:55:10.610649+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:10: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/38/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:10.611Z'
}
2025-08-15T16:55:12: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (21, 38, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 16:55:12.007831+02, 2025-08-15 16:55:12.007831+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T16:55:12: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/38/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T14:55:12.010Z'
}
2025-08-15T17:54:43: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (22, 40, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:43.079557+02, 2025-08-15 17:54:43.079557+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:43: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:43.083Z'
}
2025-08-15T17:54:44: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (23, 40, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:44.039972+02, 2025-08-15 17:54:44.039972+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:44: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:44.041Z'
}
2025-08-15T17:54:44: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (24, 40, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:44.147584+02, 2025-08-15 17:54:44.147584+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:44: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:44.148Z'
}
2025-08-15T17:54:44: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (25, 40, undefined, 0, [{"id":13,"username":"andile msani","full_name":"andile msani","..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:44.463405+02, 2025-08-15 17:54:44.463405+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:44: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:44.465Z'
}
2025-08-15T17:54:45: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (26, 40, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:45.113579+02, 2025-08-15 17:54:45.113579+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:45: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:45.114Z'
}
2025-08-15T17:54:45: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (27, 40, undefined, 0, [{"id":13,"username":"andile msani","full_name":"andile msani","..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:45.528011+02, 2025-08-15 17:54:45.528011+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:45: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:45.529Z'
}
2025-08-15T17:54:46: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (28, 40, undefined, 0, [{"id":5,"username":"Abongile Khambule","full_name":"Abongile Kh..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:46.208413+02, 2025-08-15 17:54:46.208413+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:46: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:46.209Z'
}
2025-08-15T17:54:47: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 426,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (29, 40, undefined, 0, [{"id":6,"username":"amanda gwala","full_name":"amanda gwala","r..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:47.46409+02, 2025-08-15 17:54:47.46409+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:47: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:47.465Z'
}
2025-08-15T17:54:48: Error adding employee to crew: error: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"
    at /home/production-app/production-orders-app/node_modules/pg/lib/client.js:545:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DatabaseManager.query (/home/production-app/production-orders-app/src/config/database.js:38:22)
    at async DatabaseUtils.raw (/home/production-app/production-orders-app/src/utils/database.js:146:12)
    at async MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:449:9)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20 {
  length: 428,
  severity: 'ERROR',
  code: '23514',
  detail: 'Failing row contains (30, 40, undefined, 0, [{"id":13,"username":"andile msani","full_name":"andile msani","..., t, 2025-08-15, 2025-08-15, 4, 2025-08-15 17:54:48.323825+02, 2025-08-15 17:54:48.323825+02, null).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'machine_crews',
  column: undefined,
  dataType: undefined,
  constraint: 'machine_crews_crew_letter_check',
  file: 'execMain.c',
  line: '2058',
  routine: 'ExecConstraints'
}
2025-08-15T17:54:48: Error occurred: {
  error: 'Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"',
  stack: 'Error: Failed to add employee to crew: new row for relation "machine_crews" violates check constraint "machine_crews_crew_letter_check"\n' +
    '    at MachinesService.addEmployeeToCrew (/home/production-app/production-orders-app/src/services/machines.service.js:458:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:232:20',
  url: '/api/machines/40/crews/undefined/employees',
  method: 'POST',
  user: 'admin',
  timestamp: '2025-08-15T15:54:48.325Z'
}
2025-08-15T17:54:58: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T17:54:58: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/10',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T15:54:58.613Z'
}
2025-08-15T17:54:59: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T17:54:59: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/10',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T15:54:59.672Z'
}
2025-08-15T17:55:01: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T17:55:01: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/10',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T15:55:01.734Z'
}
2025-08-15T18:00:07: Error occurred: {
  error: 'Cannot update machine while in use',
  stack: 'ValidationError: Cannot update machine while in use\n' +
    '    at MachinesService.updateMachine (/home/production-app/production-orders-app/src/services/machines.service.js:128:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:146:28',
  url: '/api/machines/26',
  method: 'PUT',
  user: 'admin',
  timestamp: '2025-08-15T16:00:07.857Z'
}
2025-08-15T18:04:30: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-15T18:10:07: ValidationError: The 'X-Forwarded-For' header is set but the Express 'trust proxy' setting is false (default). This could indicate a misconfiguration which would prevent express-rate-limit from accurately identifying users. See https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/ for more information.
    at Object.xForwardedForHeader (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:185:13)
    at wrappedValidations.<computed> [as xForwardedForHeader] (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:397:22)
    at Object.keyGenerator (/home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:658:20)
    at /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:710:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/node_modules/express-rate-limit/dist/index.cjs:691:5 {
  code: 'ERR_ERL_UNEXPECTED_X_FORWARDED_FOR',
  help: 'https://express-rate-limit.github.io/ERR_ERL_UNEXPECTED_X_FORWARDED_FOR/'
}
2025-08-15T18:10:42: JWT verification failed: jwt malformed
2025-08-15T18:11:33: JWT verification failed: jwt malformed
2025-08-15T18:15:47: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:15:47: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/7',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:15:47.980Z'
}
2025-08-15T18:15:48: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:15:48: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/9',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:15:48.370Z'
}
2025-08-15T18:15:49: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:15:49: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/7',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:15:49.047Z'
}
2025-08-15T18:15:49: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:15:49: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/9',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:15:49.430Z'
}
2025-08-15T18:15:51: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:15:51: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/7',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:15:51.112Z'
}
2025-08-15T18:15:52: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:15:52: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/9',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:15:52.647Z'
}
2025-08-15T18:16:03: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:16:03: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/7',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:16:03.895Z'
}
2025-08-15T18:16:04: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:16:04: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/9',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:16:04.419Z'
}
2025-08-15T18:16:04: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:16:04: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/7',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:16:04.959Z'
}
2025-08-15T18:16:05: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:16:05: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/9',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:16:05.489Z'
}
2025-08-15T18:16:07: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:16:07: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/7',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:16:07.018Z'
}
2025-08-15T18:16:08: Error removing employee from crew: NotFoundError: Crew not found not found
    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:474:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20 {
  statusCode: 404,
  code: 'NOT_FOUND',
  isOperational: true,
  resource: 'Crew not found'
}
2025-08-15T18:16:08: Error occurred: {
  error: 'Failed to remove employee from crew: Crew not found not found',
  stack: 'Error: Failed to remove employee from crew: Crew not found not found\n' +
    '    at MachinesService.removeEmployeeFromCrew (/home/production-app/production-orders-app/src/services/machines.service.js:492:13)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async /home/production-app/production-orders-app/src/routes/machines.routes.js:250:20',
  url: '/api/machines/40/crews/undefined/employees/9',
  method: 'DELETE',
  user: 'admin',
  timestamp: '2025-08-15T16:16:08.357Z'
}
